### ISSUE TITLE
Request quota exhaustion

### ISSUE THREAD

**Issue by yrashk** [nektro/actions-setup-zigmod#6]
Saw my CI run fail with:

```
Request quota exhausted for request GET /repos/{owner}/{repo}/releases
Retrying after 830 seconds!
Request quota exhausted for request GET /repos/{owner}/{repo}/releases
Retrying after 0 seconds!
Request quota exhausted for request GET /repos/{owner}/{repo}/releases
Retrying after 0 seconds!
```

Maybe we can add a version specification to the config so that there would be no need to list releases?

**Comment by yrashk** [comment]
See #7

**Comment by kivikakk** [comment]
I'm hitting this a lot, too: https://github.com/kivikakk/koino/runs/4909802388?check_suite_focus=true

**Comment by nektro** [comment]
will add to the docs, but this should fix it
```yml
      - uses: nektro/actions-setup-zigmod@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by nektro** [comment]
if not, i can add pulling in a token explicitly

**Comment by kivikakk** [comment]
Thanks so much! Perfect.

**Comment by kivikakk** [comment]
It seems like this is [still happening](https://github.com/kivikakk/koino/runs/4945161740?check_suite_focus=true):

```
2022-01-26T00:14:17.2454060Z ##[group]Run nektro/actions-setup-zigmod@v1
2022-01-26T00:14:17.2454430Z env:
2022-01-26T00:14:17.2455070Z   GITHUB_TOKEN: ***
2022-01-26T00:14:17.2455330Z ##[endgroup]
2022-01-26T00:14:17.4793380Z Request quota exhausted for request GET /repos/{owner}/{repo}/releases
2022-01-26T00:14:17.4793930Z Retrying after 2647 seconds!
2022-01-26T00:58:24.4752110Z Request quota exhausted for request GET /repos/{owner}/{repo}/releases
2022-01-26T00:58:24.4752430Z Retrying after 0 seconds!
2022-01-26T00:58:24.5650740Z Request quota exhausted for request GET /repos/{owner}/{repo}/releases
2022-01-26T00:58:24.5651080Z Retrying after 0 seconds!
2022-01-26T00:58:24.6357640Z Request quota exhausted for request GET /repos/{owner}/{repo}/releases
2022-01-26T00:58:24.7194670Z HttpError: API rate limit exceeded for 199.7.166.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
2022-01-26T00:58:24.7195560Z     at /Users/runner/work/_actions/nektro/actions-setup-zigmod/v1/webpack:/setup-zigmod/node_modules/@octokit/request/dist-node/index.js:86:1
2022-01-26T00:58:24.7195980Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2022-01-26T00:58:24.7196570Z     at Job.doExecute (/Users/runner/work/_actions/nektro/actions-setup-zigmod/v1/webpack:/setup-zigmod/node_modules/bottleneck/light.js:405:1)
2022-01-26T00:58:24.7226950Z ##[error]API rate limit exceeded for 199.7.166.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
2022-01-26T00:58:24.7328060Z Post job cleanup.
```

Do we maybe need to use <https://github.com/octokit/auth-action.js>?
